title: Test Twitch for Zartox & ForgFrox
description: Balbla!
theme: just-the-docs

url: https://charley3d.github.io/test-twitch/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
